// This file was autogenerated by @arrirpc/codegen-ts. Do not modify directly.
// For more information visit https://github.com/modiimedia/arri

/* eslint-disable */
// @ts-nocheck
import {
  ArriEnumValidator,
  ArriModelValidator,
  type ArriRequestOptions,
  arriRequest,
  INT8_MAX,
  INT8_MIN,
  INT16_MAX,
  INT16_MIN,
  INT32_MAX,
  INT32_MIN,
  INT64_MAX,
  INT64_MIN,
  isObject,
  serializeString,
  UINT8_MAX,
  UINT16_MAX,
  UINT32_MAX,
  UINT64_MAX,
  type Fetch,
  type $Fetch,
  createFetch,
} from "@arrirpc/client";

type HeaderMap = Record<string, string | undefined>;
export class RpcClient {
  private readonly _baseUrl: string;
  private readonly _fetch?: $Fetch;
  private readonly _headers: HeaderMap | (() => HeaderMap | Promise<HeaderMap>);
  private readonly _onError?: (err: unknown) => void;
  private readonly _options?: ArriRequestOptions;

  constructor(
    config: {
      baseUrl?: string;
      fetch?: Fetch;
      headers?: HeaderMap | (() => HeaderMap | Promise<HeaderMap>);
      onError?: (err: unknown) => void;
      options?: ArriRequestOptions;
    } = {},
  ) {
    this._baseUrl = config.baseUrl ?? "";
    if (config.fetch) {
      this._fetch = createFetch({ fetch: config.fetch });
    }
    this._headers = config.headers ?? {};
    this._onError = config.onError;
    this._options = config.options;
  }
  async sayHello(
    params: GreetingParams,
    options?: ArriRequestOptions,
  ): Promise<GreetingResponse> {
    return arriRequest<GreetingResponse, GreetingParams>({
      url: `${this._baseUrl}/say-hello`,
      method: "post",
      ofetch: this._fetch,
      headers: this._headers,
      onError: this._onError,
      params: params,
      responseFromJson: $$GreetingResponse.fromJson,
      responseFromString: $$GreetingResponse.fromJsonString,
      serializer: $$GreetingParams.toJsonString,
      clientVersion: "",
      options: options ?? this._options,
    });
  }
  async sayGoodbye(
    params: GreetingParams,
    options?: ArriRequestOptions,
  ): Promise<GreetingResponse> {
    return arriRequest<GreetingResponse, GreetingParams>({
      url: `${this._baseUrl}/say-goodbye`,
      method: "post",
      ofetch: this._fetch,
      headers: this._headers,
      onError: this._onError,
      params: params,
      responseFromJson: $$GreetingResponse.fromJson,
      responseFromString: $$GreetingResponse.fromJsonString,
      serializer: $$GreetingParams.toJsonString,
      clientVersion: "",
      options: options ?? this._options,
    });
  }
}

export interface GreetingParams {
  name: string;
}
export const $$GreetingParams: ArriModelValidator<GreetingParams> = {
  new(): GreetingParams {
    return {
      name: "",
    };
  },
  validate(input): input is GreetingParams {
    return isObject(input) && typeof input.name === "string";
  },
  fromJson(input): GreetingParams {
    let _name: string;
    if (typeof input.name === "string") {
      _name = input.name;
    } else {
      _name = "";
    }
    return {
      name: _name,
    };
  },
  fromJsonString(input): GreetingParams {
    return $$GreetingParams.fromJson(JSON.parse(input));
  },
  toJsonString(input): string {
    let json = "{";
    json += '"name":';
    json += serializeString(input.name);
    json += "}";
    return json;
  },
  toUrlQueryString(input): string {
    const queryParts: string[] = [];
    queryParts.push(`name=${input.name}`);
    return queryParts.join("&");
  },
};

export interface GreetingResponse {
  message: string;
}
export const $$GreetingResponse: ArriModelValidator<GreetingResponse> = {
  new(): GreetingResponse {
    return {
      message: "",
    };
  },
  validate(input): input is GreetingResponse {
    return isObject(input) && typeof input.message === "string";
  },
  fromJson(input): GreetingResponse {
    let _message: string;
    if (typeof input.message === "string") {
      _message = input.message;
    } else {
      _message = "";
    }
    return {
      message: _message,
    };
  },
  fromJsonString(input): GreetingResponse {
    return $$GreetingResponse.fromJson(JSON.parse(input));
  },
  toJsonString(input): string {
    let json = "{";
    json += '"message":';
    json += serializeString(input.message);
    json += "}";
    return json;
  },
  toUrlQueryString(input): string {
    const queryParts: string[] = [];
    queryParts.push(`message=${input.message}`);
    return queryParts.join("&");
  },
};
